import Head from "next/head";
import Image from "next/image";
import "bootstrap/dist/css/bootstrap.min.css";
import { Row, Col, Dropdown, Button } from "react-bootstrap";
import { Header } from "../../components/Header";

export default function CreatePost() {
  return (
    <div>
      <Head>
        <title>CreatePost</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header userId="1"/>

      <div className="container2">
        <div style={{ color: "#999", padding: "20px 0px 30px 0px" }}>
          Home / <span style={{ color: "#333" }}>Tạo bài viết</span>
        </div>

        <Row>
          <Col lg={8}>
            <Row
              style={{
                paddingBottom: "25px",
                marginRight: "58px",
                borderBottom: "1px solid #d5d4d4",
              }}
            >
              <Col lg={2}>
                <div
                  style={{
                    display: "inline-block",
                    verticalAlign: "middle",
                    lineHeight: "normal"
                  }}
                >
                  Chủ đề
                </div>
              </Col>
              <Col lg={10} style={{ paddingRight: "0px" }}>
                <Dropdown>
                  <Dropdown.Toggle
                    variant="secondary"
                    id="dropdown-basic"
                    style={{
                      backgroundColor: "white",
                      width: "100%",
                      color: "grey",
                      textAlign: "right",
                      height: "39px",
                      border: "2px solid #dcd8d8",
                    }}
                  ></Dropdown.Toggle>

                  <Dropdown.Menu style={{ width: "100%" }}>
                    <Dropdown.Item href="#/action-1">Javascript</Dropdown.Item>
                    <Dropdown.Item href="#/action-2">Công nghệ</Dropdown.Item>
                    <Dropdown.Item href="#/action-3">Thiết bị</Dropdown.Item>
                  </Dropdown.Menu>
                </Dropdown>
              </Col>
            </Row>
            <Row>
              <Col
                lg={11}
                style={{
                  padding: "25px 0",
                  borderBottom: "1px solid #d5d4d4",
                }}
              >
                <div
                  style={{
                    display: "flex",
                    padding: "0px",
                    paddingLeft: "15px",
                    backgroundColor: "#efe8e3",
                  }}
                >
                  <div style={{ flexGrow: "30", lineHeight: "38px" }}>
                    Hình ảnh
                  </div>
                  <Button style={{ flexGrow: "1" }}>+</Button>
                </div>
              </Col>
              <Col lg={1} style={{ lineHeight: "89px", paddingLeft: "16px" }}>
                <div
                  style={{
                    color: "white",
                    backgroundColor: "red",
                    textAlign: "center",
                    fontSize: "14px",
                    fontWeight: "700",
                    display: "inline-block",
                    width: "23px",
                    lineHeight: "normal",
                    borderRadius: "50%",
                    verticalAlign: "middle",
                    padding: "2px",
                  }}
                >
                  X
                </div>
              </Col>
            </Row>

            <Row>
              <Col
                lg={11}
                style={{
                  padding: "25px 0",
                }}
              >
                <h1
                  style={{
                    textAlign: "center",
                    padding: "10px",
                    border: "2px dashed rgb(212 212 212)",
                    color: "rgb(212 212 212)",
                  }}
                >
                  +
                </h1>
                <div
                  style={{
                    color: "#848484",
                    fontSize: "12px",
                    textAlign: "center",
                  }}
                >
                  Thêm tiện ích bằng cách kéo rê thành phần ở bên phải vào khung
                  trên
                </div>
              </Col>
              <Col lg={1}></Col>
            </Row>

            <Row>
              <Col lg={6}></Col>
              <Col lg={3}>
                {" "}
                <Button
                  variant="light"
                  style={{ border: "1px solid blue", color: "blue" }}
                >
                  LƯU BẢN NHÁP
                </Button>
              </Col>
              <Col lg={3}>
                {" "}
                <Button variant="primary">ĐĂNG BÀI VIẾT</Button>
              </Col>
            </Row>
          </Col>
          <Col lg={4} style={{ paddingLeft: "34px" }}>
            <div
              style={{ backgroundColor: "#f6f6f6", padding: "0 18px 0 20px" }}
            >
              <h2
                style={{
                  fontSize: "19px",
                  fontWeight: "700",
                  padding: "14px 0",
                  borderBottom: "2px solid #c1afaf",
                }}
              >
                THÊM TIỆN ÍCH
              </h2>
              <Row>
                <Col lg={6}>
                  <div
                    style={{
                      backgroundColor: "white",
                      padding: "10px 20px",
                      height: "150px",
                      marginTop: "15px"
                    }}
                  >
                    Nội dung
                  </div>
                </Col>
                <Col lg={6}>
                  <div
                    style={{
                      backgroundColor: "white",
                      padding: "10px 20px",
                      height: "150px",
                      marginTop: "15px"
                    }}
                  >
                    Nội dung
                  </div>
                </Col>
              </Row>
              <Row>
                <Col lg={6}>
                  <div
                    style={{
                      backgroundColor: "white",
                      padding: "10px 20px",
                      height: "150px",
                      marginTop: "15px"
                    }}
                  >
                    Nội dung
                  </div>
                </Col>
                <Col lg={6}>
                  <div
                    style={{
                      backgroundColor: "white",
                      padding: "10px 20px",
                      height: "150px",
                      marginTop: "15px"
                    }}
                  >
                    Nội dung
                  </div>
                </Col>
                <Col lg={6}>
                  <div
                    style={{
                      backgroundColor: "white",
                      padding: "10px 20px",
                      height: "150px",
                      marginTop: "15px"
                    }}
                  >
                    Nội dung
                  </div>
                </Col>
                <Col lg={6}>
                  <div
                    style={{
                      backgroundColor: "white",
                      padding: "10px 20px",
                      height: "150px",
                      marginTop: "15px"
                    }}
                  >
                    Nội dung
                  </div>
                </Col>
              </Row>
              <Row>
                <Col lg={6}>
                  <div
                    style={{
                      backgroundColor: "white",
                      padding: "10px 20px",
                      height: "150px",
                      marginTop: "15px"
                    }}
                  >
                    Nội dung
                  </div>
                </Col>
                <Col lg={6}>
                  <div
                    style={{
                      backgroundColor: "white",
                      padding: "10px 20px",
                      height: "150px",
                      marginTop: "15px"
                    }}
                  >
                    Nội dung
                  </div>
                </Col>
              </Row>
              <Row>
                <Col lg={6}>
                  <div
                    style={{
                      backgroundColor: "white",
                      padding: "10px 20px",
                      height: "150px",
                      marginTop: "15px"
                    }}
                  >
                    Nội dung
                  </div>
                </Col>
                <Col lg={6}></Col>
              </Row>
            </div>
          </Col>
        </Row>
      </div>
    </div>
  );
}
