import Head from "next/head";
import Image from "next/image";
import ReactPlayer from 'react-player'
import "bootstrap/dist/css/bootstrap.min.css";
import { EditorProps  } from 'react-draft-wysiwyg';
import '../../node_modules/react-draft-wysiwyg/dist/react-draft-wysiwyg.css'; 
import dynamic from 'next/dynamic';
import { Row, Col, Dropdown, Button, Form, Modal } from "react-bootstrap";
import { Header } from "../../components/Header";
import { useEffect, useRef, useState } from "react";
import icon_image from "../../assets/icon_images.png"
import icon_text from "../../assets/icon_content.png"
import icon_Video from "../../assets/icon_movie.png"
import icon_rating from "../../assets/icon_rating.png"
import icon_code from "../../assets/icon_code.png"
import icon_poll from "../../assets/icon_poll.png"
import icon_map from "../../assets/icon_map.png"
import icon_table from "../../assets/icon_calendar.png"
import icon_question from "../../assets/icon_question.png"
import icon_math from "../../assets/icon_math.jpg"



export default function CreatePost() {
  const [show, setShow] = useState(false);
  const textInput = useRef(null)
  const handleClose = () => setShow(false);
  const handleShow = () => setShow(true);
  const [image, setImage] = useState();
  const handleImage = (e) => {
    const file = e.target.files[0];
    if(file){
      file.preview = URL.createObjectURL(file);
      setImage(file)
    }
   
  }

  const Editor = dynamic<EditorProps >(
    () => import('react-draft-wysiwyg').then((mod) => mod.Editor),
    { ssr: false }
  )
  const [editor, setEditor] = useState<boolean>(false)
  useEffect(() => {
    setEditor(true)
  })
  // useEffect(() => {
  //     return () => {
  //         URL.revokeObjectURL(image)
  //     }
  // }, [image])
  return (
    <div>
      <Head>
        <title>CreatePost</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header userId="1"/>
      
      <Modal show={show} onHide={handleClose}>
        <Modal.Header closeButton>
          <Modal.Title>Video</Modal.Title>
        </Modal.Header>
        <Modal.Body>Để link video hoặc mã nhúng vào hộp thoại bên dưới
        <Form.Control type="text" placeholder="Url video" id="Url_video" ref={textInput}/>
        </Modal.Body>
        <Modal.Footer>
          <Button variant="secondary" onClick={handleClose}>
            Close
          </Button>
          <Button variant="primary" onClick={handleClose}>
            Save Changes
          </Button>
        </Modal.Footer>
      </Modal>
      
      <div className="container2">
        <div style={{ color: "#999", padding: "20px 0px 30px 0px" }}>
          Home / <span style={{ color: "#333" }}>Tạo bài viết</span>
        </div>

        <Row className="CreatePostContainer">
          <Col lg={8}>
            <Row
              className="rowContainer"
            >
              <Col lg={2}>
                <div
                  className="col2"
                >
                  Chủ đề
                </div>
              </Col>
              
              <Col lg={10} style={{ paddingRight: "0px" }}>
                <Dropdown >
                  <Dropdown.Toggle
                    variant="secondary"
                    id="dropdown-basic"
                    className="col10"
                  ></Dropdown.Toggle>

                  <Dropdown.Menu style={{ width: "100%" }}>
                    <Dropdown.Item href="#/action-1">Javascript</Dropdown.Item>
                    <Dropdown.Item href="#/action-2">Công nghệ</Dropdown.Item>
                    <Dropdown.Item href="#/action-3">Thiết bị</Dropdown.Item>
                  </Dropdown.Menu>
                </Dropdown>
              </Col>
              
            </Row>
            <Row
              className="rowContainer"
            >
              <Col lg={2}>
                <div
                  className="col2"
                >
                  Tag
                </div>
              </Col>
              
              <Col lg={10} style={{ paddingRight: "0px" }}>
              <Form.Group className="mb-3 title" controlId="title">
                <Form.Control as="textarea" rows={1} placeholder="Mỗi bài viết được gắn tối đa 4 tag"/>
              </Form.Group>
              </Col>
              
            </Row>
            <Row
              className="rowContainer"
            >
              <Col lg={2}>
                <div
                  style={{
                    display: "inline-block",
                    verticalAlign: "middle",
                    lineHeight: "normal"
                  }}
                >
                  Tiêu đề
                </div>
              </Col>
              
              <Col lg={10} style={{ paddingRight: "0px" }}>
              <Form.Group className="mb-3 title" controlId="title">
                <Form.Control as="textarea" rows={1} />
              </Form.Group>
              </Col>
              
            </Row>
            <Row className="rowContainer"
            >
              <Col lg={2}>
                <div className="col2">
                  Sơ lược
                </div>
              </Col>
              <Col lg={10} style={{ paddingRight: "0px" }}>
              <Form.Group className="mb-3 title" controlId="title">
                <Form.Control as="textarea" rows={3} placeholder="140-170 ký tự đầu tiên có thể xuất hiện trong kết quả tìm kiếm."/>
              </Form.Group>
              </Col>
              
            </Row>
            <Row className="MediaContainer">
              <Col
                lg={11}
                className="item-container"
              >
                <div
                  className="item"
                >
                  
                  <div style={{ flexGrow: "30", lineHeight: "38px" }}>
                    Hình ảnh
                  </div>
                  <input type="file" 
                    onChange={handleImage }  
                    style={{display:"none"}}   
                  />
                  <Button style={{ flexGrow: "1" }} onClick={ ()=>{
                        const input = document.querySelector('input[type="file"]') as HTMLInputElement;
                        input.click();
                    }}>+</Button>
                </div>
              </Col>
              
              <Col lg={1} style={{ lineHeight: "89px", paddingLeft: "16px" }}>
                <div
                   className="deleteIcon"
                >
                  X
                </div>
              </Col>
              {image && (
                    <img src={image.preview} alt=""></img>
                )
                }
            </Row>
            <Row className="MediaContainer">
              <Col
                lg={11}
                className="item-container"
              >
                <div
                  className="item"
                >
                  
                  <div style={{ flexGrow: "30", lineHeight: "38px" }}>
                    Video
                  </div>
                  <Button 
                      style={{ flexGrow: "1" }}
                      onClick={handleShow} >+</Button>
                </div>
              </Col>
              
              <Col lg={1} style={{ lineHeight: "89px", paddingLeft: "16px" }}>
                <div
                  className="deleteIcon"
                >
                  X
                </div>
              </Col>
              { 
                
                (textInput.current != null && textInput.current.value) && (
                <ReactPlayer url={textInput.current.value}/>
              )
              }
            </Row>
            <Row className="TextContainer">
              <Col
                lg={11}
                className="item-container"
              >
                <div
                  className="item"
                >
                  
                  <div style={{ flexGrow: "30", lineHeight: "38px" }}>
                    Nội dung
                  </div>
                </div>
                {editor ? (
                    <Editor
                        wrapperClassName="wrapper-class"
                        editorClassName="editor-class"
                        toolbarClassName="toolbar-class"
                        toolbar={{
                            options: ['inline', 'blockType', 'fontSize', 'list', 'textAlign', 'fontFamily', 'colorPicker','emoji','history'],
                            inline: { inDropdown: true },
                            list: { inDropdown: true },
                            textAlign: { inDropdown: true },
                            link: { inDropdown: true },
                            history: { inDropdown: true }
                        }}
                    />) : null}
              </Col>
              
              <Col lg={1} style={{ lineHeight: "89px", paddingLeft: "16px" }}>
                <div
                  className="deleteIcon"
                >
                  X
                </div>
              </Col>
              
            </Row>
            <Row>
              <Col
                lg={11}
                style={{
                  padding: "25px 0",
                }}
              >
                <h1
                  style={{
                    textAlign: "center",
                    padding: "10px",
                    border: "2px dashed rgb(212 212 212)",
                    color: "rgb(212 212 212)",
                  }}
                >
                  +
                </h1>
                <div
                  style={{
                    color: "#848484",
                    fontSize: "12px",
                    textAlign: "center",
                  }}
                >
                  Thêm tiện ích bằng cách kéo rê thành phần ở bên phải vào khung
                  trên
                </div>
              </Col>
              <Col lg={1}></Col>
            </Row>

            <Row>
              <Col lg={6}></Col>
              <Col lg={3}>
                {" "}
                <Button
                  variant="light"
                  style={{ border: "1px solid blue", color: "blue" }}
                >
                  LƯU BẢN NHÁP
                </Button>
              </Col>
              <Col lg={3}>
                {" "}
                <Button variant="primary">ĐĂNG BÀI VIẾT</Button>
              </Col>
            </Row>
          </Col>
          <Col lg={4} style={{ paddingLeft: "34px" }}>
            <div
              style={{ backgroundColor: "#f6f6f6", padding: "0 18px 20px 20px" }}
            >
              <h2
                style={{
                  fontSize: "19px",
                  fontWeight: "700",
                  padding: "14px 0",
                  borderBottom: "2px solid #c1afaf",
                }}
              >
                THÊM TIỆN ÍCH
              </h2>
              <Row>
                
                <Col lg={6}>
                  <div
                    style={{
                      backgroundColor: "white",
                      padding: "10px 20px",
                      height: "150px",
                      marginTop: "15px"
                    }}
                  >
                    <Image src={icon_text} width={150} height={150}></Image>
                  </div>
                </Col>
                <Col lg={6}>
                  <div
                    style={{
                      backgroundColor: "white",
                      padding: "10px 20px",
                      height: "150px",
                      marginTop: "15px"
                    }}
                  >
                    <Image src={icon_image} width={150} height={150}></Image>
                  </div>
                </Col>
              </Row>
              <Row>
                <Col lg={6}>
                  <div
                    style={{
                      backgroundColor: "white",
                      padding: "10px 20px",
                      height: "150px",
                      marginTop: "15px"
                    }}
                  >
                    <Image src={icon_Video} width={150} height={150}></Image>
                  </div>
                </Col>
                <Col lg={6}>
                  <div
                    style={{
                      backgroundColor: "white",
                      padding: "10px 20px",
                      height: "150px",
                      marginTop: "15px"
                    }}
                  >
                    <Image src={icon_poll} width={150} height={150}></Image>
                  </div>
                </Col>
                <Col lg={6}>
                  <div
                    style={{
                      backgroundColor: "white",
                      padding: "10px 20px",
                      height: "150px",
                      marginTop: "15px"
                    }}
                  >
                  <Image src="https://www.seekpng.com/png/detail/444-4449289_diagram-png-diagram-icon.png" alt="Diagram Png - Diagram Icon@seekpng.com" width={150} height={150}/> 
                  </div>
                </Col>
                <Col lg={6}>
                  <div
                    style={{
                      backgroundColor: "white",
                      padding: "10px 20px",
                      height: "150px",
                      marginTop: "15px"
                    }}
                  >
                    <Image src={icon_map} width={150} height={150}></Image>
                  </div>
                </Col>
              </Row>
              <Row>
                <Col lg={6}>
                  <div
                    style={{
                      backgroundColor: "white",
                      padding: "10px 20px",
                      height: "150px",
                      marginTop: "15px"
                    }}
                  >
                    <Image src={icon_table} width={150} height={150}></Image>
                  </div>
                </Col>
                <Col lg={6}>
                  <div
                    style={{
                      backgroundColor: "white",
                      padding: "10px 20px",
                      height: "150px",
                      marginTop: "15px"
                    }}
                  >
                    <Image src={icon_math} width={150} height={150}></Image>
                  </div>
                </Col>  
              </Row>
              <Row>
                <Col lg={6}>
                  <div
                    style={{
                      backgroundColor: "white",
                      padding: "10px 20px",
                      height: "150px",
                      marginTop: "15px"
                    }}
                  >
                  <Image src={icon_question} width={150} height={150}></Image>
                  </div>
                </Col>
                <Col lg={6}>
                  <div
                    style={{
                      backgroundColor: "white",
                      padding: "10px 20px",
                      height: "150px",
                      marginTop: "15px"
                    }}
                  >
                    <Image src={icon_rating} width={150} height={150}></Image>
                  </div>
                </Col>
              </Row>
              <Row>
              </Row>
            </div>
          </Col>
        </Row>
      </div>

    </div>
  );
}
