import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import "bootstrap/dist/css/bootstrap.min.css";
import { Row, Col, ListGroup } from "react-bootstrap";

import Post from "../../components/post";
import { Header } from "../../components/Header";
import { EditProfile } from "../../components/EditProfile";
import { ChangePassWord } from "../../components/ChangePassWord";
import { useEffect, useState } from "react";
import { Follower } from "../../components/Follower";
import Draft from "../../components/draft";

export default function Dashboard() {
  let classHead = "head";

  const [content, setContent] = useState("article");
  const [listPosts, setListPosts] = useState(null);

  useEffect(() => {
    fetch('/api/post')
    .then(response => response.json())
    .then(data => {
      let list = data[0].posts.concat(data[1].posts, data[2].posts);
      setListPosts(list);
    });
  }, []);

  function DashBoardContent(){
    if(content == "article"){
      return (
        <>
        <h3>DANH SÁCH BÀI VIẾT ĐÃ ĐĂNG</h3>
          {listPosts&&listPosts.slice(0, 8).map((post) => {
          return <Post thumbnail={post.thumbnail || ""} title={post.title} author={post.author.name} avatar={post.author.avatar} />;
        })}
        </>
      );
    }
    else if(content == "changePassword"){
      return(
        <>
           <h3>ĐỔI MẬT KHẨU</h3>
           <ChangePassWord/>
        </>
      );
    }
    else if(content == "profile"){
      return (
        <>
          <h3>ĐỔI MẬT KHẨU</h3>
          <EditProfile/>
        </>
      );
    }
    else if(content == "follow"){
      return(
        <>
          <h3>NGƯỜI THEO DÕI</h3>
          <Follower/>
          <Follower/>
        </>
      );
    }
    else if(content == "follower"){
      return(
        <>
          <h3>NGƯỜI ĐANG THEO DÕI</h3>
          <Follower/>
          <Follower/>
        </>
      );
    }
    else if(content == "draft"){
      return (
        <>
        <h3>BÀI VIẾT NHÁP</h3>
         <Draft/>
         <Draft/>
         <Draft/>
         <Draft/>
        </>
      );
    }
    else {
      return(
        <>
        </>
      );
    }
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header userId="1"/>

      <div className="container2">
        <div style={{ color: "#999", padding: "20px 0px 30px 0px" }}>
          Home / Tài khoản cá nhân /{" "}
          <span style={{ color: "#333" }}>Quản lý tài khoản</span>
        </div>
        <Row>
          <Col lg={3} className="dashboard-menu">
            <ul>
              <li className={(content == "article" ||content == "draft") ? (classHead + " head-active") : classHead }>Quản lí nội dung</li>
              <li>
                <ul>
                  <li 
                    className={(content == "article") ? "item-active" : "" }
                    onClick={()=>{
                    setContent("article")
                  }}
                  >Bài viết đã đăng</li>
                  <li
                    className={(content == "draft") ? "item-active" : "" }
                    onClick={()=>{
                    setContent("draft")
                    }}
                  >Bài viết nháp</li>
                  <li>Bảng tin đã đăng</li>
                </ul>
              </li>
              <li className={(content == "profile" || content == "changePassword" || content =="follow" || content == "follower" || content == "bookmark") ? (classHead + " head-active") : classHead }>Quản lí tài khoản</li>
              <li>
                <ul>
                  <li 
                    className={(content == "profile") ? "item-active" : "" }
                    onClick={()=>{
                    setContent("profile")
                  }}>Thông tin cá nhân</li>
                  <li
                    className={(content == "changePassword") ? "item-active" : "" }
                    onClick={()=>{
                    setContent("changePassword")
                  }}
                  >Đổi mật khẩu</li>
                  <li
                    className={(content == "follow") ? "item-active" : "" }
                    onClick={()=>{
                    setContent("follow")
                  }}
                  >Người theo dõi</li>
                  <li
                    className={(content == "follower") ? "item-active" : "" }
                    onClick={()=>{
                    setContent("follower")
                  }}
                  >Người đang theo dõi</li>
                  <li
                    className={(content == "bookmark") ? "item-active" : "" }
                    onClick={()=>{
                    setContent("bookmark")}}
                  >Bookmark</li>
                </ul>
              </li>
              <li className="head">Quản lí cấp bậc</li>
              <li>
                <ul>
                  <li>Trạng thái</li>
                </ul>
              </li>
            </ul>
          </Col>
          <Col lg={9} className="dashboard-body">
            {DashBoardContent()}
          </Col>
        </Row>
      </div>
    </div>
  );
}
